################################################################
# Description:  Playbook to restore base file that were      ###
#               edited in the weblogic patching playbook.    ###
#               Files restored: bash_profile,                ###
#               setDomainEnv.sh,                             ###
#               and start_derby.sh                           ###
# Enviroment:   Dev & Test                                   ###
# Version:      1                                            ###
# Filename:     restore_web.yaml                             ###
################################################################

# Comment out this section if using test_web.yaml to call playbook
# Start
#---
#- hosts: dt
##  vars:
##    current_java: '/opt/java/hotspot/8/64_bit/jdk1.8.0_202/'
##    latest_java: '/opt/java/hotspot/8/64_bit/jdk1.8.0_1337/'
##    current_weblogic: 'WL_HOME="/opt/weblogic/wl1213_190115/wlserver"'
##    latest_weblogic: 'WL_HOME="/opt/weblogic/wl1213_1337/wlserver"'
#  tasks:
# End


# Kill Derby
    - name: Check if kill_derby.sh exists
      stat:
        path: /o/y/zowner/scripts/kill_derby.sh
      register: kderby_script

    - name: Copy over Kill_derby.sh
      copy:
        src: /etc/ansible/scripts/kill_derby.sh
        dest: /o/y/zowner/scripts/kill_derby.sh
        owner: zowner
        group: zowner
        mode: 0755
      when: kderby_script.stat.exists == false

    - name: Kill Derby
      shell: "bash /o/y/zowner/scripts/kill_derby.sh"
      async: 10
      poll: 0
      when: kderby_script.stat.exists == true


# Kill WebLogic
    - name: Check if kill_weblogic.sh exists
      stat:
        path: /o/y/zowner/scripts/kill_weblogic.sh
      register: kweblogic_script

    - name: Copy over Kill_weblogic.sh
      copy:
        src: /etc/ansible/scripts/kill_weblogic.sh
        dest: /o/y/zowner/scripts/kill_weblogic.sh
        owner: zowner
        group: zowner
        mode: 0755
      when: kweblogic_script.stat.exists == false


    - name: kill weblogic
      shell: "bash /o/y/zowner/scripts/kill_weblogic.sh"
      async: 10
      poll: 0
      when: kweblogic_script.stat.exists == true

# Delete Scripts used
    - name: Delete Kill WebLogic Script
      file:
        path: /o/y/zowner/scripts/kill_weblogic.sh
        state: absent

    - name: Delete Kill Derby Script
      file:
        path: /o/y/zowner/scripts/kill_derby.sh
        state: absent

# Restore Bash Profile
    - name: Find Latest Bash Profile
      shell: find /o/y/zowner/ -name ".bash_profile*" | xargs grep -li '{{ current_java }}' |xargs ls -t | head -1
      register: nfile

    - name: Get the File name of Latest Bash Profile
      set_fact:
        pfile: "{{ nfile.stdout }}"

    - name: Restore Bash Profile
      copy:
        src: "{{ pfile }}"
        dest: /o/y/zowner/.bash_profile
        remote_src: yes
        mode: 0755
        backup: yes


# Restore Start Derby Script
    - name: Find Latest Start Derby
      shell: find /o/y/zowner/scripts/ -name "start_derby.sh*" | xargs grep -li '{{ current_java }}' |xargs ls -t | head -1
      register: nderby

    - name: Get the File name of Latest Start Derby
      set_fact:
        pderby: "{{ nderby.stdout }}"

    - name: Restore Start Derby Script
      copy:
        src: "{{ pderby }}"
        dest: /o/y/zowner/scripts/start_derby.sh
        remote_src: yes
        mode: 0755
        backup: yes

# Restore SetDomain.sh
    - name: Find Latest setDomainEnv.sh
      shell: find /o/y/zowner/domain/{{zowner_DOMAIN}}/bin/ -name "setDomainEnv.sh*" | xargs grep -li '{{ current_java }}' |xargs ls -t | head -1
      register: nsetdomainenv

    - name: Get the File name of Latest SetDomain
      set_fact:
        psetdomainenv: "{{ nsetdomainenv.stdout }}"

    - name: Restore SetDomain
      copy:
        src: "{{ psetdomainenv }}"
        dest: /o/y/zowner/domain/{{zowner_DOMAIN}}/bin/setDomainEnv.sh
        remote_src: yes
        mode: 0755
        backup: yes

# Start Derby
#    - name: start derby
#      shell: "(bash /o/y/zowner/scripts/start_derby.sh &)"
#      async: 10
#      poll: 0

# Start WebLogic
#    - name: start weblogic
#      shell: "(bash /o/y/zowner/domain/{{zowner_DOMAIN}}/startWebLogic.sh &)"
#      async: 10
#      poll: 0

# Source Bash
#    - name: Source Bash Profile
#      shell: "source /o/y/zowner/.bash_profile"
#      async: 10
#      poll: 0

