#################################################################
# Description:  Playbook to call botht e weblogic patching    ###
#               playbook and restore playbook.  Testing       ###
#               purpose                                       ###
#  Enviroment:  Dev & Test                                    ###
# Version:      1                                             ###
# Filename:     test_web.yaml                                 ###
#################################################################

---
- hosts: dt
  tasks:

    - name: Run Edit Playbook
      include: weblogic_java_patching.yaml

    - name: Run Restore Playbook
      include: restore_web.yaml

